export const portfolioData = [
  {
    id: 1,
    title: "The Technicals",
    url: "https://the-technicals.herokuapp.com/",
    github: "https://github.com/kelseybrianne/tech-blog",
    image: require("../assets/images/technicals-homepage.png"),
    alt: "Tech Blog homepage",
    description: "A tech blog for all things tech.",
  },
  {
    id: 2,
    title: "Portfolio",
    url: "https://kelseybrianne.github.io/portfolio/",
    github: "https://github.com/kelseybrianne/portfolio",
    image: require("../assets/images/portfolio-screenshot.png"),
    alt: "Portfolio homepage",
    description: "My portfolio v1.0",
  },
  {
    id: 3,
    title: "Work Day Scheduler",
    url: "https://kelseybrianne.github.io/day-planner/",
    github: "https://github.com/kelseybrianne/day-planner",
    image: require("../assets/images/day-planner-screenshot.png"),
    alt: "Work Day Scheduler homepage",
    description: "Plan your work day.",
  },
  {
    id: 4,
    title: "JATE",
    url: "https://basic-pwa-text-editor.herokuapp.com/",
    github: "https://github.com/kelseybrianne/pwa-text-editor",
    image: require("../assets/images/text-editor-homepage.png"),
    alt: "JATE Homepage",
    description: "Just another text editor.",
  },
  {
    id: 5,
    title: "Code Quiz",
    url: "https://kelseybrianne.github.io/code-quiz/",
    github: "https://github.com/kelseybrianne/code-quiz",
    image: require("../assets/images/code-quiz-screenshot.png"),
    alt: "Code quiz homepage",
    description: "Test your HTML, JavaScript, and CSS skills!",
  },
  {
    id: 6,
    title: "Dailies",
    url: "https://kelseybrianne.github.io/dailies/",
    github: "https://github.com/kelseybrianne/dailies",
    image: require("../assets/images/dailies-screenshot.png"),
    alt: "Dailies homepage",
    description: "A simple task tracker.",
  }
];
